apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service.yaml
- preview-service.yaml
images:
- name: schoolofdevops/vote
  newName: pravinladkat16/vote
  newTag: bb59e96
